"""
Molecule Converter — interconvert between molecular representations.
"""
import streamlit as st
import pandas as pd
from rdkit import Chem
from rdkit.Chem import rdMolDescriptors
from rdkit.Chem.inchi import MolToInchi, MolFromInchi, InchiToInchiKey

from pipeline.visualization import mol_to_image

st.title("Molecule Converter")
st.write(
    "Convert between SMILES, InChI, InChIKey, and molecular formula. "
    "Paste a single molecule for a full conversion card, or switch to Batch mode "
    "to process many molecules at once."
)

with st.expander("About these representations"):
    st.markdown(
        """
| Representation | Description | Best for |
|---|---|---|
| **SMILES** | Line notation encoding atoms and bonds as a string | Input to ML models, database storage, copy-paste |
| **Canonical SMILES** | Unique, standardised SMILES generated by RDKit — same molecule always gives the same string | Deduplication, exact-match searching |
| **Isomeric SMILES** | Canonical SMILES that also encodes stereochemistry (`@`, `/`, `\\`) | Chiral molecules, 3D-aware workflows |
| **InChI** | IUPAC standard identifier; layered, verbose, unambiguous | Cross-database lookup, archiving |
| **InChIKey** | 27-character hash of the InChI — fixed length, safe for indexing | Database keys, web search, hashing |
| **Molecular Formula** | Atom count string (e.g. C₉H₈O₄) | Quick composition check |
        """
    )

# ── Mode selector ────────────────────────────────────────────────────────────
mode = st.radio("Mode", ["Single molecule", "Batch conversion"], horizontal=True)

# ── Helpers ──────────────────────────────────────────────────────────────────

def _detect_and_parse(text: str):
    """
    Auto-detect input type and return (mol, input_type, error).
    Supports SMILES and InChI.
    """
    text = text.strip()
    if not text:
        return None, None, "Empty input."
    if text.startswith("InChI="):
        mol = MolFromInchi(text)
        if mol is None:
            return None, "InChI", f"Could not parse InChI: {text}"
        return mol, "InChI", None
    else:
        mol = Chem.MolFromSmiles(text)
        if mol is None:
            return None, "SMILES", f"Could not parse SMILES: {text}"
        return mol, "SMILES", None


def _mol_to_representations(mol):
    """Return a dict of all representations for a molecule."""
    canonical = Chem.MolToSmiles(mol, isomericSmiles=True)
    non_isomeric = Chem.MolToSmiles(mol, isomericSmiles=False)
    inchi = MolToInchi(mol) or "N/A"
    inchikey = InchiToInchiKey(inchi) if inchi != "N/A" else "N/A"
    formula = rdMolDescriptors.CalcMolFormula(mol)
    return {
        "canonical_smiles": canonical,
        "isomeric_smiles": non_isomeric if non_isomeric != canonical else None,
        "inchi": inchi,
        "inchikey": inchikey,
        "formula": formula,
    }


# ── MODE 1: Single molecule ───────────────────────────────────────────────────
if mode == "Single molecule":
    st.subheader("Single Molecule Conversion")
    st.caption(
        "Paste a SMILES string (e.g. `CC(=O)Oc1ccccc1C(=O)O`) or an InChI string "
        "(starting with `InChI=`). The input type is detected automatically."
    )

    col_input, col_btn = st.columns([5, 1])
    with col_input:
        user_input = st.text_input(
            "SMILES or InChI",
            placeholder="CC(=O)Oc1ccccc1C(=O)O  or  InChI=1S/...",
            label_visibility="collapsed",
        )
    with col_btn:
        convert = st.button("Convert", type="primary", use_container_width=True)

    if not (convert or user_input):
        st.stop()

    if not user_input.strip():
        st.warning("Please enter a SMILES or InChI string.")
        st.stop()

    mol, input_type, error = _detect_and_parse(user_input)

    if error:
        st.error(error)
        st.stop()

    st.success(f"Detected input type: **{input_type}**")

    reps = _mol_to_representations(mol)

    st.divider()
    img_col, id_col = st.columns([1, 2])

    with img_col:
        png = mol_to_image(mol, size=(300, 300))
        st.image(png, caption="2D Structure")

    with id_col:
        st.markdown("**Canonical SMILES**")
        st.code(reps["canonical_smiles"], language=None)

        if reps["isomeric_smiles"] is not None:
            st.markdown("**Non-isomeric SMILES** *(differs from canonical — molecule has stereocentres)*")
            st.code(reps["isomeric_smiles"], language=None)

        st.markdown("**Molecular Formula**")
        st.code(reps["formula"], language=None)

        st.markdown("**InChI**")
        st.code(reps["inchi"], language=None)

        st.markdown("**InChIKey**")
        st.code(reps["inchikey"], language=None)


# ── MODE 2: Batch conversion ──────────────────────────────────────────────────
else:
    st.subheader("Batch Conversion")
    st.caption("Enter one SMILES per line, or upload a .txt / .csv / .xlsx file.")

    uploaded_file = st.file_uploader(
        "Upload file", type=["txt", "csv", "xlsx"], label_visibility="collapsed"
    )
    pasted = st.text_area("Or paste SMILES here (one per line)", height=150)

    if st.button("Convert All", type="primary"):
        smiles_list = []

        if uploaded_file is not None:
            fname = uploaded_file.name.lower()
            if fname.endswith(".csv") or fname.endswith(".xlsx"):
                df_up = pd.read_csv(uploaded_file) if fname.endswith(".csv") else pd.read_excel(uploaded_file)
                smiles_col = None
                for candidate in ["canonical_smiles", "SMILES", "Smiles", "smiles"]:
                    if candidate in df_up.columns:
                        smiles_col = candidate
                        break
                if smiles_col is None:
                    smiles_col = st.selectbox("Select the SMILES column", df_up.columns.tolist())
                smiles_list = df_up[smiles_col].dropna().astype(str).tolist()
            else:
                content = uploaded_file.read().decode("utf-8")
                smiles_list = [l.strip() for l in content.splitlines() if l.strip()]
        elif pasted.strip():
            smiles_list = [l.strip() for l in pasted.splitlines() if l.strip()]

        if not smiles_list:
            st.warning("Please upload a file or paste at least one SMILES string.")
            st.stop()

        rows = []
        n_failed = 0
        for smi in smiles_list:
            mol = Chem.MolFromSmiles(smi)
            if mol is None:
                rows.append({
                    "Input_SMILES": smi,
                    "Canonical_SMILES": "PARSE ERROR",
                    "InChI": "",
                    "InChIKey": "",
                    "Molecular_Formula": "",
                })
                n_failed += 1
                continue
            reps = _mol_to_representations(mol)
            rows.append({
                "Input_SMILES": smi,
                "Canonical_SMILES": reps["canonical_smiles"],
                "InChI": reps["inchi"],
                "InChIKey": reps["inchikey"],
                "Molecular_Formula": reps["formula"],
            })

        result_df = pd.DataFrame(rows)
        n_ok = len(smiles_list) - n_failed

        st.write(f"**{n_ok}** converted successfully, **{n_failed}** failed to parse.")
        st.dataframe(result_df, use_container_width=True)

        from datetime import datetime
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        st.download_button(
            "Download conversion table as CSV",
            data=result_df.to_csv(index=False),
            file_name=f"molecule_conversions_{ts}.csv",
            mime="text/csv",
        )
